# Generated by Django 6.0.3 on 2026-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
