# Generated by Django 6.0.3 on 2026-03-08 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_song_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="is_free",
            field=models.BooleanField(
                default=True, help_text="Uncheck to make this a paid track"
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Set price if not free (e.g., 1.99)",
                max_digits=6,
            ),
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.song"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "song")},
            },
        ),
    ]
